#!/bin/bash
# Install an application and start with foreman
APP_HOME=/app
BUILD_HOME=~/build
SOURCE_HOME=$BUILD_HOME/source

app=$1

do_exit() {
  echo $2
  exit $1
}

install_buildpack() {
  pack=$1
  rm -rf $BUILD_HOME/buildpack
  git clone $pack $BUILD_HOME/buildpack
  $BUILD_HOME/buildpack/bin/compile $SOURCE_HOME $BUILD_HOME/cache
}


[ -z "$app" ] && do_exit 1 "No app url specified"

git clone $app $SOURCE_HOME

buildpack="$(cat $SOURCE_HOME/.buildpacks)"
for bp in $(echo $buildpack)
do
  install_buildpack $bp
done

#foreman export
