#!/bin/bash
# Install an application and start with foreman
APP_HOME=/app
BUILD_HOME=~/build
SOURCE_HOME=$BUILD_HOME/source

app=$1

do_exit() {
  echo $2
  exit $1
}

install_buildpack() {
  pack=$1
  rm -rf $BUILD_HOME/buildpack
  git clone $pack $BUILD_HOME/buildpack
  $BUILD_HOME/buildpack/bin/compile $SOURCE_HOME $BUILD_HOME/cache
}


[ -z "$app" ] && do_exit 1 "No app url specified"

mkdir -p /app/log
git clone $app $SOURCE_HOME

buildpack="$(cat $SOURCE_HOME/.buildpacks)"
for bp in $(echo $buildpack)
do
  install_buildpack $bp
done

echo "SOURCE_HOME=$SOURCE_HOME" >> /etc/profile
cat >> /etc/profile <<'EOT'
if [ -d "$SOURCE_HOME/.profile.d" ]
then
  for f in $(ls $SOURCE_HOME/.profile.d/)
  do
    source $SOURCE_HOME/.profile.d/$f
  done
fi
#[ -f "$SOURCE_HOME/environment.sh" ] && source $SOURCE_HOME/environment.sh
EOT

if [ -d "$SOURCE_HOME/.supervisor.d" ]
then
  cp $SOURCE_HOME/.supervisor.d/*.conf /etc/supervisor/conf.d/
fi
supervisorctl reread

